### ISSUE TITLE
useradd requires --no-log-init option in images/Dockerfile as a workaround for https://github.com/moby/moby/issues/5419

### ISSUE THREAD

**Issue by Qronen** [IARSystems/bx-docker#1]
See: https://github.com/moby/moby/issues/5419

Without `useradd --no-log-init` and while user has very large user id value (e.g. 200000000), the `docker build` will hang until all hard disk space on the host is consumed.

Here is a fix proposal:

> diff --git a/images/Dockerfile b/images/Dockerfile
index 5053cb5..6bf059c 100644
--- a/images/Dockerfile
+++ b/images/Dockerfile
@@ -43,8 +43,9 @@ ENV  IAR_BUILD_PATH="/build"
 ENV  PATH="${IAR_BX_PATH}/${BX_ARCH}/bin:${IAR_BX_PATH}/common/bin:$PATH" # Create the image with an user named `iaruser` using the same UID from the host's user
-# For convenience, the user `iaruser` will be added to the "sudo" group
-RUN  useradd --create-home --uid ${USER_ID} iaruser && \
+# For convenience, the user `iaruser` will be added to the "sudo" group
+# --no-log-init is needed due: https://github.com/moby/moby/issues/5419
+RUN  useradd --no-log-init --create-home --uid ${USER_ID} iaruser && \
      echo "iaruser:iaruser" | chpasswd && \
      adduser iaruser sudo

**Comment by felipe-iar** [comment]
Hi @Qronen 

Thanks for reporting. We will look into this issue.

**Comment by felipe-iar** [comment]
Hi again @Qronen 

I created a new branch, eligible be merged to the default branch containing, among other [changes](https://github.com/IARSystems/bx-docker/compare/dev-next-patch), the flag for the image user as you have suggested.

From my end, everything seems to be working fine when using an user with a  very high UID, starting from the image creation up to actually building the projects.

Would you mind testing the new branch from your end?
Here is the direct URL to branch I'm referring to: [dev-next-patch](https://github.com/IARSystems/bx-docker/tree/dev-next-patch).

I appreciate your feedback.

Felipe

**Comment by Qronen** [comment]
`docker build` works as expected with this change, and the image works for my purposes.
