### ISSUE TITLE
setup-license

### ISSUE THREAD

**Issue by soboforsee** [IARSystems/bx-docker#12]
Hi ,

environnement jenkins/docker

I have create a docker that contains IAR bxramfs compiler.
I have a network license.
I have no problem into the container when I use : lightlicensemanager setup -s myhost
but I try to setup the license in a docker volume like in the setup script.
I create a volume
I run/exec a container with  lightlicensemanager setup -s myhost
I remove the container.
than I launch my jenkins pipeline that used the IAR docker image and add in argument -v LMS2:/usr/local/etc/IARSystems
the first time it works, but now I have an error message License already in use.
I check I have no other pipeline / docker image running.

How can I share the network license over several docker image ?
If I used lightlicensemanager setup in my container, and launch a new build , it failed because the license is not release.

thank you
Sohphie

**Comment by felipe-iar** [comment]
Hi Sohphie,

Thanks for the detailed description.

My guess is that the containers are being run with ephemeral hostnames which will take the first 48-bit of the CONTAINER_ID as their hostnames.

When running the containers within the jenkins build server, please try setting them to use the build server's hostname.
https://github.com/IARSystems/bx-docker/blob/4e825b56db825b777b97acb1d5c3c361d4040de9/run#L42

Newly spawned containers should be able to rely on the same license configuration.

**Comment by soboforsee** [comment]
Hi Felipe,

So after further test it was not the hostmane , It works without passing it in argument.
In fact our Jenkins also run in a Docker image so , first I try to do the setup-license on the server thar running jenkins but in fact I need to run the setup-license in a jenkins pipeline , which pipeline launch docker run command.

Sophie

**Comment by soboforsee** [comment]
Sorry I need to reopen,

after some times (20min) I relaunch the pipeline and I have the error "license already in use" 
I will retry with hostname, to be sure

**Comment by soboforsee** [comment]
So I need the two modifications
- license setup from a pipeline
-  use the same hostname for all iar image
