### ISSUE TITLE
A new CI/CD friendly product line with new licenses and no cloud support?

### ISSUE THREAD

**Issue by khorabb** [IARSystems/bx-docker#18]
I am sorry to be so pessimistic but I have reported this issue several times with very little follow-up. How does the `bx*` product line help anyone when the licensing models does not allow builds in the cloud? 

As the readme states:
```
An IAR LMS2 License Server
    with activated license(s) for the product in the .deb package,
    reachable from the Linux machine.
```
This is not feasible in any cloud use case. Then the build is strictly local on owned machines the switch to linux has marginal benefits imo.

**Comment by david-iar** [comment]
Please reach out to fae.emea@iar.com for further discussion on the IAR LMS2 License Server and possible use in a cloud scenario.
