### ISSUE TITLE
Fatal Error[LMS001]: License check failed. Use the IAR License Manager to resolve the problem. 

### ISSUE THREAD

**Issue by graugans** [IARSystems/bx-docker#20]
Is there a single command to check if a licence is available? Currently I do get 108 Errors related to a missing license on each source file which shall be build.

BTW this licence management is a real pain to use in an automated build environment.

**Comment by felipe-iar** [comment]
The error `[LMS001]` means that, from the compiler perspective, the license was not set.

The simplest solution I can think of right now is a initial stage in the pipeline with the concept in the snippet below. The core idea would be to verify if the compiler pass the license check before actually start using it.

```bash
#!/bin/bash

/opt/iarsystems/bxarm/arm/bin/iccarm --version > /dev/null 2>&1

if [ $? -eq 0 ]; then
  echo "License working..."
else
  echo "Something wrong... check license."
fi
```

Would that work for you?

We are sorry for any incovenience regarding the License Management System. Our devs are currently reengineering the LMS infrastructure. In the future, the current solution might be simplified, or provide tighter integration with CI/cloud environments.

**Comment by KubaHyzicki** [comment]
If anyone needed it, short script prepared after Iar support suggested to use nwlics command
`licenseName='ARMBX.EW'
usedLicenseInfo=$(lightlicensemanager nwlics | grep "${licenseName}" | cut -d' ' -f4)
usedLicenses=$(sed 's/\/.//' <<< "${usedLicenseInfo}")
availableLicenses=$(sed 's/.\///' <<< "${usedLicenseInfo}")
echo "${usedLicenses}/${availableLicenses}"
if [[ ("${usedLicenses}" -lt "${availableLicenses}") && ("${availableLicenses}" -gt 0) ]]; then
    echo true
else
    echo false
fi`

**Comment by felipe-iar** [comment]
Thanks for sharing your script, @KubaHyzicki. I updated your comment just to make it more readable as an entire block.

**Comment by ambativ** [comment]
It is good idea to use "nwlics" command option to check available licenses but when we tried to run the same command - LightLicenseManager.exe nwlics, we are getting empty list.

PS C:\workspace\Embedded Workbench 9.0\common\bin> .\LightLicenseManager.exe nwlics
Product Ver Used Ch out Server Expires License Number
------- --- ---- ------ ------ ------- --------------


May I know, is there really limitation to run the command in container (windows or Linux) environment or some settings really needed

**Comment by felipe-iar** [comment]
@ambativ Thanks for your question.
This symptom generally might be related to missing the license setup step on the client-side. Try this:
```
....\EW\common\bin> .\LightLicenseManager setup -s <license-server-ipv4>
```
Replacing `<license-server-ipv4>` for the actual IAR License Server IP address which provides the license for the product in use.

**Comment by ambativ** [comment]
@felipe-iar Thanks for prompt response.

I have already setup the license on the client side and confirmed with " .\LightLicenseManager products " command. It is working as expected and showing product, version, license number, license server ip.

but when we run .\LightLicenseManager nwlics, it is showing nothing in container environment.
