### ISSUE TITLE
LightLicenseManager does not show Network Licenses from a Windows Container

### ISSUE THREAD

**Issue by felipe-iar** [IARSystems/bx-docker#30]
This issue started to be discussed in #20 by @ambativ.
Since it is a different topic, I moved the discussion to this specific issue.

### Summary
The command `LightLicenseManager nwlics` returns an empty table when invoked from a Windows container as below:
```
PS C:\workspace\Embedded Workbench 9.0\common\bin> .\LightLicenseManager.exe nwlics
Product Ver Used Ch out Server Expires License Number
------- --- ---- ------ ------ ------- --------------
```

**Comment by felipe-iar** [comment]
@anbativ Can you please provide more information regarding this issue?
- Base Microsoft's image used
- IAR product/version and how it was installed in the container.

**Comment by ambativ** [comment]
@felipe-iar, 
 Windows Container :
-----------------------
1. Base Image : mcr.microsoft.com/windows-cssc/python3.7.2windows:ltsc2019
2.  IAR Product ARM.EW/9.10
3. We copied extracted IAR for ARM embedded workbench to container and run ..\ew\setup.exe silently and setup license
4. Even we tried by creating docker volume with locally installed workbench on Windows host

**Comment by felipe-iar** [comment]
Thanks for your reply @ambativ. Can you run `\path\to\arm\bin\iccarm.exe --version` without license issues in your setup?

**Comment by ambativ** [comment]
@felipe-iar ,

![image](https://github.com/IARSystems/bx-docker/assets/144887824/ba42f9ac-2db3-44d3-8e59-cf444efbab50)

**Comment by felipe-iar** [comment]
Thanks. Can you please check the contents of `%PROGRAMDATA%/IARSystems/LicenseManagement/Settings/CommonSettings.xml`?

**Comment by ambativ** [comment]
@felipe-iar, Below is the content. In place of ip_address, my actual License Server IP is there.
<?xml version="1.0" encoding="UTF-8"?>

-<settings>

<AddedServer0>ip_address</AddedServer0>

</settings>

**Comment by felipe-iar** [comment]
@ambativ thanks again. Please try this workaround and run `LightLicenseManager nwlics` again in the interactive container:
```xml
<settings>
    <EnableBroadcasts>1</EnableBroadcasts>
    <AddedServer0>NNN.NNN.NNN.NNN</AddedServer0>
</settings>
```
And let me know if that worked.
PS: I edited your previous comment only to make it visible in markdown.

**Comment by ambativ** [comment]
@felipe-iar, still the same issue even after updating CommonSettings.xml file

**Comment by felipe-iar** [comment]
Hi @ambativ. 

At the moment, there are 2 clients for the IAR License Server: `LicenseManager.eze` (GUI) and `LightLicenseManager.exe` (CLI).

I was able to reproduce this exact issue from my end when on 9.10.1 (ships with LightLicenseManager 2.17.4).
Upgrading to 9.40.1 (ships with LightLicenseManager 2.18.5) resolved the issue.
Can you test with the latest version?

> __Note__ The IAR License Server I tested with runs on the latest version ([2.18.3](https://www.iar.com/knowledge/support/technical-notes/licensing/iar-license-server-tools-lms2/)), which is the recommended.

**Comment by ambativ** [comment]
May I know why the issue with IAR 9.10.1 and LightLicenseManager 2.17.4? Is it possible to update LightLicenseManager version alone?

**Comment by felipe-iar** [comment]
That's a good question. As far as I can tell newer versions should serve old compilers. There might be limits or setbacks. Of course, going that direction will certainly void several warranties, deep into uncharted waters. If you are willing to go that far at your risk, you could [download an evaluation for 9.40.1](https://www.iar.com/products/architectures/arm/iar-embedded-workbench-for-arm/iar-embedded-workbench-for-arm---free-trial-version/), install it normally, and try replacing the LightLicenseManager.exe client on your current image installation. If that works for you, let me know.

**Comment by ambativ** [comment]
@felipe-iar, Thanks. I could see network license details with nwlics under windows container after upgrading to 9.40.1 
( LightLicenseManager 2.18.5).

**Comment by felipe-iar** [comment]
Great to hear @ambativ! Glad you found a way for it to work on your end. Thanks for providing feedback.

**Comment by britt1010** [comment]
Hey @felipe-iar

I have been for a while searching for the IAR arm/msp430 tools install commands. Let me explain background of the issue. For few of the projects we using IAR tool chains for arm/msp430. We decided to bring those in CI/CD pipeline and maintain IAR installers in container.

I am struggling for a while to get commands to install IAR in containers. I think you are my savior and luckily, I got this forum.

Seems this issue got closed. Let me know if I want to open new ticket. In Brief what i need is, IAR tool installation command which i can use either in windows or Linux containers preferably via Dockerfile.

Regards,
Britt

**Comment by felipe-iar** [comment]
Hey @britt1010
 
Even if technically possible, the IAR Embedded Workbench was not explicitly  designed with server/headless scenarios in mind, so in every way you need to first check your license's terms of use.

Here a couple ideas that might be useful for your use case:
* Idea 1

We have a relatively recent product, the IAR Build Tools for Arm (BXARM) which since v9.20 comes with silent install options. For example, in the Dockerfile:
```dockerfile
COPY bxarm-9.20.4.exe C:/bxarm-9.20.4.exe
RUN  Start-Process -Wait -FilePath "C:/bxarm-9.20.4.exe" -ArgumentList "/hide_usd /autoinstall"
```
* Idea 2

For earlier installers, you might try generating an InstallShield replay script from the extracted `setup.exe`. The file is generally extracted to the `%TEMP%` folder and can be found via "Explore Installation Media" for the "CD installers" that come with Autorun.exe. For that, you need to install it on the host once to record the install wizard's chosen steps to a file. For example:
```
setup -r -f1C:\DockerContext\ew_response.iss
```
And then, in the Dockerfile, copy the *.iss file alongside the setup.exe from the Docker context to the image and run the installer, similarly to this:
```dockerfile
COPY setup.exe C:/setup.exe
COPY ew_response.iss C:/ew_response.iss
RUN  Start-Process -Wait -FilePath "C:/setup.exe" -ArgumentList "-s -f1C:/ew_response.iss"
```

>__Note__ These are only a couple of ideas that might work or not for Windows containers. They were not tested thoroughly from our end. From the few tests I ran around Windows containers, I simply installed BXARM inside the Docker context in a custom directory, removed everything I did not need from the context, built the image, and then uninstalled from the host.

>__Note__ Without hesitation, I'd always recommend Linux containers for all things Docker. Unfortunately there is currently no IAR product for MSP430 that runs natively on Linux.

I hope it helps. Feel free to reach out to us at fae@iar.com if you need more information.

**Comment by britt1010** [comment]
I will get in touch through fae@iar.com. One doubt I have, Is it possible to install IAR tools in windows container without admin privileges?

Generally when we install on windows host, it will ask for admin privileges which we need to enter. How to overcome that in windows container, any option available?

Regards,
Britt

**Comment by felipe-iar** [comment]
Thanks.

Regarding the InstallShield-based installers for Embedded Workbench: No. Currently all the IAR products installs to `%PROGRAMFILES%`. By design, they require administrative privileges as they will also install support drivers and such.

**Comment by britt1010** [comment]
@felipe-iar I could see from this issue conversation you and @ambativ were able to install IAR ARM in docker context. If so can either you provide steps?

Regards, 
Britt

**Comment by ambativ** [comment]
Hi @britt1010 I didn't install IAR in container. I created docker volume of IAR installed on local windows host and mount it to windows container.
